### ISSUE TITLE
Take right/left alignment into account when layout=rows

### ISSUE THREAD

**Issue by BurningTreeC** [BurningTreeC/tiddlywiki-muuri#2]
Thanks to @canne we now have a row-based layout.

We still need to take into account if items are aligned right-to-left or left-to-right which the rows-layout doesn't do at the moment

**Comment by canne** [comment]
Hi,

Correct. in (Western) book writing scope of mine one does think about that... Should not be too difficult to experiment by forking https://codepen.io/petrim/pen/qBaNjGq first (in a TiddlyWiki it is a pain), I'll see what I can do and keep my repo synced with yours, meanwhile.

One question regarding the requirements in general: do you plan to revive `muuri-tiddler-width` attribute present in the early days?

I find it actually quite useful (like with PDF-files in Node.js) but if it comes back it will complexify the current, simple algorithms, leading perhaps into a new functional requirements, such as aligning by **_columns_**. (I would throw my hands up! 😁 )

I'll try to write my book first with the new function but when got stuck, will give this fix some time. Meanwhile, let's keep this issue open for however fixes it first.

Thanks again for the great work which all TiddlyWiki users should be aware of!

**Comment by BurningTreeC** [comment]
Hi, I'm having a hard time remembering how the `muuri-tiddler-width` attribute worked, but I wanted to add the possibility to make single tiddlers a different width than the column-width - if you mean something like that.

**Comment by canne** [comment]
Right, the `muuri-tiddler-width` attribute was a field one was able to define as an integer number of muuri column widths for a tiddler, like this (from a 2017/8 Node.js archive of mine), this one being a PDF-article:
![Screenshot 2020-12-13 201350](https://user-images.githubusercontent.com/6381128/102021424-068dda00-3d80-11eb-8875-748f9ef845ee.jpg)
An example use case: I work on a big screen with chapter synopsis tiddlers, side by side, number of muuri columns is eight:
```
| A | B | C | D | E | F | G | H |
```
Now, I need to read an article `Z` which I have saved and set to  have a `muuri-tiddler-width` of `4`, it will open like this:
```
|         Z         | A | B | C | D |
|         Z         | E | F | G | H |
|         Z         | 
```
Which is pretty cool, since otherwise the PDF-file would remain too narrow to be readable.

It is not a big deal  with today's `tiddlywiki-muuri` to use `Alt+arrowLeft` to expand the PDF but a) it is not very intuitive and b) the preceding method was automatic = when you close `Z` everything returns back to one single, nicely readable row.

This feature would bring a totally new aspect to the customized row sorting algorithm and frankly it sounds too mind boggling for me to start spanning the rows / columns in that simple loop The sorting remains certainly doable, but one would need to create some real-life use cases for this requirement.

I would rather fix the left alignment issue of row based horizonal alignment without the `muuri-tiddler-width` attribute, or similar and only after it start pondering what to do with the variable column width and eventual spanning rules.

**Comment by canne** [comment]
Like this for the right aligned rows? [codepen.io/petrim/pen/KKgaeyw](codepen.io/petrim/pen/KKgaeyw)
<img width="872" alt="Screenshot 2020-12-13 234000" src="https://user-images.githubusercontent.com/6381128/102026246-fa644580-3d9c-11eb-92a4-0720dcb87f48.png">

That would make one more custom layout method. Would be easier than fiddling a complex algorithm in one.

Do you agree on comment line 26: _i.e._ calculating the width of the tiddlers (see above discussion) to determine the right edge or do you prefer to give me the client width and what that is? Supposing that you start using `muuri-tiddler-width` or similar that would have its importance. Or we just start like presented.

**Comment by BurningTreeC** [comment]
Genius! Thanks for the pen, I'll integrate this asap.

About the `muuri-tiddler-width` - I was thinking about realizing it using CSS only, I'll give it a try today

Thanks @canne
